name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.7
    - name: Run script
      run: bash scripts/test_all.sh
